name = "Sohail Mahmud"
license = ""
licenselink = "https://github.com/soahilsami/sm-blog/blob/master/LICENSE.md"
description = "Sohail's Blog"
homepage = "https://sohailsami.netlify.app/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.73.0"

[author]
  name = "Luiz F. A. de Prá"
  homepage = "https://sohailsami.netlify.app"
