name = "Sohail"
license = "MIT"
licenselink = "https://github.com/sohailsami/sohailsami.github.io/blob/master/LICENSE.md"
description = "A simple and clean blog theme for Blogging"
homepage = "https://sohailsami.github.io"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.73.0"

[author]
  name = "Sohail Mahmud"
  homepage = "https://sohailsami.github.io"
